name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: 安装依赖
        run: flutter pub get

      - name: 构建 Windows 可执行文件
        run: flutter build windows --release

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: real-esrgan-gui-windows-build
          path: build/windows/runner/Release/
