name: Build Real-ESRGAN-GUI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build executable
        run: flutter build windows --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: real-esrgan-gui-build
          path: build/windows/runner/Release/
